# -*- coding: utf-8 -*-
"""mic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4uEyBiUL8hWBP1uKrGKP3dhXoonjZg-
"""





import streamlit as st
import speech_recognition as sr
import os

st.title("🎤 Voice Command to Text")

if st.button("Start Recording"):
    st.info("🎙️ Speak now...")

    # Use recognizer and microphone
    recognizer = sr.Recognizer()
    mic = sr.Microphone()

    with mic as source:
        recognizer.adjust_for_ambient_noise(source)
        audio = recognizer.listen(source, timeout=5)

    try:
        text = recognizer.recognize_google(audio)
        st.success(f"📝 You said: {text}")
    except sr.UnknownValueError:
        st.error("❌ Couldn't understand what you said.")
    except sr.RequestError:
        st.error("❌ Could not connect to the recognition service.")

